### ISSUE TITLE
Anyone wanna swap repo stars for project 1?

### ISSUE THREAD

**Issue by noahmbenjamin** [mikeizbicki/cmc-csci145-math166#101]
Hi! Since we need to each have at least 5 stars on our repo for project 1, does anybody wanna put their repo link down below and I'll star it, and then maybe you can star mine?

Thanks!

https://github.com/NBLEGO/Noah-Benjamin-Project-1-CSCI145

**Comment by Yugi00** [comment]
Hey, great idea! Starred your repo and if you could star mine that would be great! Thanks!

https://github.com/Yugi00/CSCI145-Project-1

**Comment by KAVentura** [comment]
Hey! I starred your repos; if you could star mine, that would be appreciated. Thanks!

https://github.com/KAVentura/Pagerank.py

**Comment by nessakiani** [comment]
Hey, I also just starred it! Could you please star mine? Thank you!

[https://github.com/nessakiani/Pagrank](Pagerank)
