### ISSUE TITLE
Lambda server not opening Jupyter Notebook

### ISSUE THREAD

**Issue by ZiangXue** [mikeizbicki/cmc-csci145-math166#108]
Whenever I try to start up Jupyter notebook by the command given in the project page, I get a:

```
Error executing Jupyter command 'notebook': [Errno 2] No such file or directory
```

I assume this is due to some issue in the Jupyter package. Has anyone seen this error? How did u get around it?

**Comment by DestrosCMC** [comment]
If this is still giving you issues, try running:
```
pip install notebook
```

**Comment by ZiangXue** [comment]
Unfortunately that did not help. Something seems to be wrong with a setup file:

```
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Mw5_OK/terminado/
```

**Comment by RuiluGao** [comment]
I was able to solve this issue by running
```
pip3 install notebook
``` 

However, after running the notebook command, I was able to get a link for my jupyter notebook but I couldn't open it in the browser (I could open the file when I am in the local folder though)

Pretty sure I did port forwarding on localhost:8080 but I was given a link that looks like
```
http://localhost:8890/?token=208dbf33ee8e67ba1ccb8d82abeb2f42b28c74b15929e6af
```
Mike, do you know what issue I might run into?

**Comment by mikeizbicki** [comment]
@RuiluGao The url you posted shows that it is using lambda server port 8890 and so 8080 is the wrong port to forward.
