### ISSUE TITLE
Links for jupyter notebook not working

### ISSUE THREAD

**Issue by Yugi00** [mikeizbicki/cmc-csci145-math166#110]
When trying to open up the jupyter notebook, the links I am given are no longer working. When I initially try to open the notebook, I am given:
    [I 22:53:04.797 NotebookApp] Writing notebook server cookie secret to /home/runner/.local/share/jupyter/runtime    /notebook_cookie_secret
    [I 22:53:06.750 NotebookApp] Serving notebooks from local directory: /home/runner/Project2
    [I 22:53:06.751 NotebookApp] Jupyter Notebook 6.4.3 is running at:
    [I 22:53:06.751 NotebookApp] http://localhost:8888/?token=f31b28bcb0272cec284272f643ee729ee33179e9368f8e80
    [I 22:53:06.751 NotebookApp]  or http://127.0.0.1:8888/?token=f31b28bcb0272cec284272f643ee729ee33179e9368f8e80
    [I 22:53:06.751 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
    [W 22:53:06.832 NotebookApp] No web browser found: could not locate runnable browser.
    [C 22:53:06.833 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/runner/.local/share/jupyter/runtime/nbserver-39-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=f31b28bcb0272cec284272f643ee729ee33179e9368f8e80
     or http://127.0.0.1:8888/?token=f31b28bcb0272cec284272f643ee729ee33179e9368f8e80

However, the links that I am given are not working when trying to open the notebook. I have tried disabling my firewall, but it is still unable to work. Is there something I'm doing wrong?

**Comment by mikeizbicki** [comment]
Closing because there's not enough info here to resolve the issue, and I believe we discussed this after class.
