### ISSUE TITLE
Project Halfspaces

### ISSUE THREAD

**Issue by sophiahuangg** [mikeizbicki/cmc-csci145-math166#112]
Hi Mike! There's 10 of us working on the project together right now - we were wondering if it's possible for our class to get an extension for the project or if it's possible for an extra office hours session tomorrow? Thank you!

**Comment by afroCoderHanane** [comment]
+1 this

**Comment by laurenleadbetter** [comment]
Would it be possible to get an extension until Sunday?

**Comment by livrenfro** [comment]
^boost

**Comment by hstuart23** [comment]
would be very helpful!

**Comment by RuiluGao** [comment]
+1 as well!

**Comment by Bhargavaa1** [comment]
+1 this issue.

**Comment by kevinm126** [comment]
+1 ✋🏽

**Comment by mikeizbicki** [comment]
Sorry I didn't see this until now.  Everyone in class can have an extension until this Sunday.
