### ISSUE TITLE
Running the Project on Lambda: CUDA out of memory, while there are plenty memory left

### ISSUE THREAD

**Issue by ZiangXue** [mikeizbicki/cmc-csci145-math166#126]
I'm running the transfer learning project on the Lambda server, and I'm getting this error in model.train:

```
RuntimeError: CUDA out of memory. Tried to allocate 1.08 GiB (GPU 0; 10.76 GiB total capacity; 170.74 MiB already allocated; 9.75 GiB free; 184.00 MiB reserved in total by PyTorch)
```

This doesn't really make sense, it says there are 9.75 GiB free. Did it happen to any of you? What machine are you running the notebook on?

**Comment by mikeizbicki** [comment]
Hmmm... this is weird.  Sorry I didn't see this earlier where we could have talked about it in class.  Hopefully you got this resolved, but if not, you can just disable CUDA in your code.  The lambda server's 80 CPUs will be just as fast (or faster) than a GPU on the transfer learning.
