### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by sophiahuangg** [mikeizbicki/cmc-csci145-math166#128]
Hi Mike! I'm getting an error that says OSError: [Errno 23] Too many open files in system when I try to run in Jupyter Notebook for second Train and Evaluate part. (I'm not opening any other new files while running) I was wondering if you had any suggestions on how to get around this?

**Comment by mikeizbicki** [comment]
I'm not sure what you're referring to here.  You haven't given me enough information to reproduce the problem, and there's nothing we've been working on recently involving jupyter.

**Comment by sophiahuangg** [comment]
Just resolved it - sorry about that!
