### ISSUE TITLE
OH Proposal

### ISSUE THREAD

**Issue by sophiahuangg** [mikeizbicki/cmc-csci145-math166#131]
Hi Mike!

Can I propose for office hours this Wednesday 9am - 11am and/or Thursday from 1pm-3pm?

**Comment by nickwilson3** [comment]
I'd like to propose Tuesday 1-3pm as well

**Comment by chuckrak** [comment]
Can I propose Thursday from 11-12?

**Comment by mikeizbicki** [comment]
I'm not available on Wednesday, and it seemed like early Thursday generally worked better for everyone before, so let's do Thursday 11-12.

**Comment by kingeddy11** [comment]
Can I propose to extend Thursday's office hours to 10 - 12

**Comment by mikeizbicki** [comment]
Yes, we'll extend tomorrow's review session to 10AM-12PM.  See you all then :)
