### ISSUE TITLE
Lambda Server Disk Quota Exceeded

### ISSUE THREAD

**Issue by chuckrak** [mikeizbicki/cmc-csci145-math166#137]
I'm trying to run the updated version of the pagerank on the Lambda server.  I get the following error when I run the pagerank file:

```
cerb2020@lambda-server:~/final$ python3 pagerank.py --data=./data/lawfareblog.csv.gz --search_query='weapons'
INFO:gensim.downloader:Creating /home/cerb2020/gensim-data
[--------------------------------------------------] 0.6% 9.5/1662.8MB downloadedTraceback (most recent call last):
  File "pagerank.py", line 272, in <module>
    g = WebGraph(args.data, filter_ratio=args.filter_ratio)
  File "pagerank.py", line 28, in __init__
    self.vectors = gensim.downloader.load('word2vec-google-news-300')
  File "/home/cerb2020/.local/lib/python3.6/site-packages/gensim/downloader.py", line 496, in load
    _download(name)
  File "/home/cerb2020/.local/lib/python3.6/site-packages/gensim/downloader.py", line 396, in _download
    urllib.urlretrieve(url_data, dst_path, reporthook=_progress)
  File "/usr/lib/python3.6/urllib/request.py", line 281, in urlretrieve
    tfp.write(block)
OSError: [Errno 122] Disk quota exceeded
```

I tried cleaning the disk space by removing everything that I have on the lambda server, but I still am getting the error. 
Here are the outputs of suggested debugging commands I found online.
```
cerb2020@lambda-server:~$ ls -l
total 8
drwxrwxr-x 2 cerb2020 cerb2020 4096 Dec  5 20:37 final
drwxrwxr-x 2 cerb2020 cerb2020 4096 Dec  5 20:38 gensim-data
```

```
cerb2020@lambda-server:~$ df -h 
Filesystem      Size  Used Avail Use% Mounted on
udev            126G     0  126G   0% /dev
tmpfs            26G  3.9M   26G   1% /run
/dev/nvme0n1p2  1.8T  1.6T   68G  96% /
tmpfs           126G   20K  126G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           126G     0  126G   0% /sys/fs/cgroup
/dev/nvme0n1p1  511M  4.4M  507M   1% /boot/efi
/dev/sda1        48T   44T  1.3T  98% /data
tmpfs            26G   12K   26G   1% /run/user/1070
tmpfs            26G     0   26G   0% /run/user/1149
tmpfs            26G     0   26G   0% /run/user/1151
tmpfs            26G     0   26G   0% /run/user/1125
tmpfs            26G     0   26G   0% /run/user/1067
tmpfs            26G     0   26G   0% /run/user/1200
tmpfs            26G   12K   26G   1% /run/user/1003
tmpfs            26G     0   26G   0% /run/user/1186
tmpfs            26G     0   26G   0% /run/user/1196
```

```
cerb2020@lambda-server:~$ quota 
Disk quotas for user cerb2020 (uid 1196): 
     Filesystem  blocks   quota   limit   grace   files   quota   limit   grace
 /dev/nvme0n1p2 2097152* 1048576 2097152   6days   25773       0       0        
```

**Comment by mikeizbicki** [comment]
You can check which folders in your home folder are consuming space with the following command:
```
$ du -hd1 /home/cerb2020
516M	./.local
142M	./.cache
8.0K	./.links2
8.0K	./.emacs.d
28K	./gensim-data
16K	./final
8.0K	./.gnupg
658M	.
```
The `.local` folder contains libraries you've installed with `pip install`.  The `.cache` folder contains the raw downloaded files from pypi that pip downloads before installing them.  Both folders can be safely deleted.

These are hidden folders, which is why your `ls -l` command didn't see them.  In the future, adding the `-a` (short for all) flag to `ls` will display all the files.

**Comment by chuckrak** [comment]
I was initially successful with removing ```.local``` and ```.cache```, however, I realized that the model I was using may have been not feasible on the server (1.6GB),  so I tried to delete `.local` and `.cache` again and use a model of smaller size. However, when I went to re-install the necessary `pip` packages, I was no longer able to do so. [was able to earlier].

Below are the new maximum sizes I am able to get `.local` / `.cache` to before receiving the same error regarding disk quota.
```
cerb2020@lambda-server:~$ du -hd1 /home/cerb2020
5.2M	/home/cerb2020/.local
62M	/home/cerb2020/.cache
8.0K	/home/cerb2020/.links2
8.0K	/home/cerb2020/.emacs.d
28K	/home/cerb2020/gensim-data
28K	/home/cerb2020/final
8.0K	/home/cerb2020/.gnupg
67M	/home/cerb2020
```
Also attached is quota command
```
cerb2020@lambda-server:~$ quota
Disk quotas for user cerb2020 (uid 1196): 
     Filesystem  blocks   quota   limit   grace   files   quota   limit   grace
 /dev/nvme0n1p2 1951684* 1048576 2097152   6days     459       0       0        
```

**Comment by afroCoderHanane** [comment]
+1 to chucks issue, I am also having disk quota exceeded. I even try to use a venv and run into even more trouble. my initial issue was related to gensim, even after I `use pip install gensim`, it still couldn't find the module. I had the same error for halfspaces polynomial with torch and just decided to use my laptop instead. when, I try running my code on my laptop it does work but I can't feed it data.

**Comment by mikeizbicki** [comment]
@chuckrak Hmmm... I've verified that you can only create files of 142MB for some reason even though your quota limit is 2GB.  I'm not sure why that's the case.  In any event, I've upped your limit to 10GB, so this shouldn't be a problem anymore.

@afroCoderHanane I've also increased your limit to 10GB.

**Comment by QuinceyWilliams** [comment]
+1 to this issue. Would it be possible to get the limit increase as well?

**Comment by mikeizbicki** [comment]
@QuinceyWilliams I've increased your limit to 10G.

**Comment by hfmandell** [comment]
+1 as well!

**Comment by kevinm126** [comment]
+1^

**Comment by mikeizbicki** [comment]
@hfmandell @kevinm126 I've updated both of your accounts to have a limit of 10GB.

**Comment by KAVentura** [comment]
+1

**Comment by mikeizbicki** [comment]
@KAVentura I've increased your limit to 10GB.

**Comment by Bhargavaa1** [comment]
+1^

**Comment by mikeizbicki** [comment]
@Bhargavaa1 Your limit is now 10GB.

**Comment by DestrosCMC** [comment]
+1

**Comment by mikeizbicki** [comment]
@DestrosCMC I've increased your limit.

**Comment by nickwilson3** [comment]
I have also ran out of disc space, can I have my limit increased to 10 GB as well?

**Comment by livrenfro** [comment]
\+ 1

**Comment by samchotzen** [comment]
+1

**Comment by mikeizbicki** [comment]
@nickwilson3 @livrenfro @samchotzen I've increased the limit on all of your accounts.

**Comment by cristywei** [comment]
+1

**Comment by mikeizbicki** [comment]
@cristywei I've increased the limit on your account.

**Comment by nessakiani** [comment]
+1

**Comment by mikeizbicki** [comment]
@nessakiani I've increased your limit :)

**Comment by danimonz** [comment]
+1

**Comment by mikeizbicki** [comment]
@sparevibes I've increased your limit.
