### ISSUE TITLE
Proposal for Extra Finals Review Session

### ISSUE THREAD

**Issue by kingeddy11** [mikeizbicki/cmc-csci145-math166#142]
Hi Mike,

I wanted to propose an extra finals review session for tomorrow Thursday morning from 10 am - noon.

**Comment by nickwilson3** [comment]
+1

**Comment by mikeizbicki** [comment]
I won't be available for the full two hours, but I can do from 11am-noon.

**Comment by mikeizbicki** [comment]
Additionally, as a reminder, there is office hours from 11am-noon on Friday where you all are welcome to ask questions about the final.
