### ISSUE TITLE
Link for Assignment Submission on Sakai for Word2Vec Pagerank Assignemt

### ISSUE THREAD

**Issue by afroCoderHanane** [mikeizbicki/cmc-csci145-math166#144]
Hey @mikeizbicki, 
Is it possible to have a link for the submission for the word2vec assignment, it is currently unavailable on Sakai. Thanks :) .

**Comment by mikeizbicki** [comment]
Eeek, this should be fixed now.

There will be no late penalties applied for this assignment, but you should have your submission completed before your final exam in order to get your final grade at that point.
