### ISSUE TITLE
Midterm Prep this Friday (09/20)

### ISSUE THREAD

**Issue by sybf-pro** [mikeizbicki/cmc-csci145-math166#159]
Let's make this coming Friday a dedicated office hours for the midterm prep. I will attend, anyone else?

**Comment by bbell25cmc** [comment]
I would go between 10-11 or 12-3!

**Comment by LukeF2** [comment]
I can make it between 9-12.

**Comment by mvalsania** [comment]
I support the idea. I can make it any time between 3:30pm and 11:59pm

**Comment by kt-k10** [comment]
I can do any time 12:30 to 5:30 and would also love to attend!

**Comment by sybf-pro** [comment]
I can do 9 - 1030 am and 12 - 2 pm. I have work from 2 - 5 pm.

**Comment by missangie23** [comment]
I have class from 11-1150am and a job from 10-11pm. I would love to do anytime in between: 12pm-10pm.

**Comment by nicholaslasko123** [comment]
That would be great! I can do anytime from 10am-5pm.

**Comment by brookefeinberg** [comment]
I can make it anytime between 12-4:30pm and would love to come!

**Comment by avagreyyy4** [comment]
I would love to come! I can make anytime 9-11:30am or 4:30pm+

**Comment by fi0112358** [comment]
I would also love to join! I'm free from 9-10 and then 3:30 onwards

**Comment by YiqiSun1** [comment]
I would join anytime is good

**Comment by YiqiSun1** [comment]
I would love to join. Anytime is good for me

**Comment by mikeizbicki** [comment]
I've updated the office hours at https://github.com/mikeizbicki/cmc-csci145-math166/issues/150#issuecomment-2361496155
