### ISSUE TITLE
Problem 8 (iii)

### ISSUE THREAD

**Issue by ethanashby** [mikeizbicki/cmc-csci145-math166#16]
Hello,

I am confused by problem 8 (iii)... considering the result of our homework last week (xT*x)^k is O(n) for dense vectors. If we represent y^k=x^2^k=(xT*x)^2^(k-1) won't this mean that y^k=O(n), or linear time? Then how do we represent the time in terms of k?

**Comment by mikeizbicki** [comment]
That's a good question.  The main thing to notice is that the superscripts on the x variables are not exponentiation, but indexing.  So your formula `x^2^k=(xTx)^2^(k-1)` is incorrect.  

The answer for 8.3 is analogous to the answer for 7.2.  You are repeating the previous step $K$ times, and so you multiply the runtime of the previous step by $K$.
