### ISSUE TITLE
can't finish project.... gensim / scripy issues?

### ISSUE THREAD

**Issue by bbell25cmc** [mikeizbicki/cmc-csci145-math166#168]
my code hasn't been able to download for an hour. this gensim has prevented me from coding for four hours??????

**Comment by bbell25cmc** [comment]
I've been trying to get this gensim thing to work since 6pm. I've downloaded so many things for it, and it still can't download enough for me to download scripy, so I can't run any of part 2. I would like to request an extension.

**Comment by mikeizbicki** [comment]
Sorry, I can't give an extension for this reason as you've had 2 weeks to get problems like this resolved.  Recall that the late penalty is:

> You lose 2**(i-1) points on every assignment, where i is the number of days late.

So you can still complete the assignment and get most of the points.  The QCL will have mentors who can get this type of problem resolved.
