### ISSUE TITLE
Lecture videos (2024-09-18, Now]?

### ISSUE THREAD

**Issue by mvalsania** [mikeizbicki/cmc-csci145-math166#172]
Hello everyone, does anyone know where to find the recordings for the last few lectures? Thank you!

**Comment by mikeizbicki** [comment]
Hmmm... it looks like all the videos were uploaded, but there was a problem with them getting added to the playlist.  I've fixed this, and the playlist in #148 should have all the videos now.  Sorry about that.

**Comment by mvalsania** [comment]
No worries, thank you so much!
