### ISSUE TITLE
Coding assignment 1 - Repo Links

### ISSUE THREAD

**Issue by jknaudt21** [mikeizbicki/cmc-csci145-math166#18]
Hi friends,

In order to make all of our lives easier I decided to create this issue. Drop your repo link (even if its empty) so people can start giving  them stars.

Here's mine: https://github.com/jknaudt21/DM_HW1
I'll do my best to star you back!

**Comment by selina-28030** [comment]
https://github.com/selina-28030/csci145_01b

**Comment by ashleywangg** [comment]
https://github.com/ashleywangg/DM-PageRank

**Comment by ReymonP** [comment]
https://github.com/ReymonP/Pagerank-Project

**Comment by jinkim22** [comment]
https://github.com/jinkim22/PageRank

**Comment by hanaknight** [comment]
https://github.com/sabhartono/PageRank

**Comment by elizabethsong** [comment]
https://github.com/elizabethhh/page-rank

**Comment by gPlacide** [comment]
https://github.com/gPlacide/Pagerank

**Comment by karmishthaseth** [comment]
https://github.com/karmishthaseth/MATH166-PageRank

**Comment by wklein21** [comment]
https://github.com/wklein21/pagerank

**Comment by adhityavenkatraman** [comment]
https://github.com/adhityavenkatraman/PageRank

**Comment by natashawong** [comment]
https://github.com/natashawong/pagerank

**Comment by ethanashby** [comment]
https://github.com/ethanashby/Lawfare_blog_search

**Comment by ethanashby** [comment]
https://github.com/ethanashby/Lawfare_blog_search

**Comment by samuellee19** [comment]
https://github.com/samuellee19/CSCI145_PageRank

**Comment by oliverc1623** [comment]
https://github.com/oliverc1623/PageRank

**Comment by daagcentral** [comment]
https://github.com/gtihtina/page_rank_1

**Comment by kielong** [comment]
https://github.com/kielong/Pagerank

**Comment by sarahbashir** [comment]
https://github.com/sarahbashir/pagerank

**Comment by jzhuge99** [comment]
https://github.com/jzhuge99/PageRank

**Comment by jrod2699** [comment]
https://github.com/jrod2699/PageRank-

**Comment by nsamko** [comment]
https://github.com/nsamko/pagerank

**Comment by ma-alvarado** [comment]
https://github.com/ma-alvarado/PagerankRepo

**Comment by nmpatterson22** [comment]
https://github.com/nmpatterson22/Pagerank

**Comment by cschulz21** [comment]
https://github.com/cschulz21/Pagerank

**Comment by cj2467** [comment]
https://github.com/cj2467/Pagerank

**Comment by samesoul** [comment]
https://github.com/samesoul/PageRank

**Comment by cnorth21** [comment]
https://github.com/cnorth21/Pagerank

Star for star ;)

**Comment by mvanis** [comment]
https://github.com/mvanis/PageRank

I only [had] 2 stars,
Thanks everyone!

**Comment by jleonard21** [comment]
https://github.com/jleonard21/PageRank

**Comment by benfig1127** [comment]
https://github.com/benfig1127/Pagerank

**Comment by benfig1127** [comment]
Hey everyone, I still only have 3 stars, would love if two more people could star my repo :)
https://github.com/benfig1127/Pagerank

**Comment by flancast90** [comment]
Hi, just found this repo through an advanced search, would any of you all care to be so kind as to star any of my repos you're interested in? 
I have quite a few "cool" ones (at least in my opinion), such as a Spotify Tool, Browser Extension for GitHub, Primer Finder Algo, and more. 
I've given some of the linked projects above some stars already!

**Comment by al-yakubovich** [comment]
https://github.com/al-yakubovich/Punctuation_Restorator

Star for Star!
