### ISSUE TITLE
Error in HW Code?

### ISSUE THREAD

**Issue by kjiang25** [mikeizbicki/cmc-csci145-math166#186]
In the calculate_error_vs_m function for our hw, I am getting an error from the following line.

ax1.set_xscale('log', basex=2)
TypeError: LogScale.__init__() got an unexpected keyword argument 'basex'.

The code works when I remove the input argument basex=2, but I am wondering if this is the correct implementation. Please let me know.

**Comment by mvalsania** [comment]
I changed all the basex=2 to base=2 and it seems like it is working now.

**Comment by kjiang25** [comment]
Works for me too, thanks!
