### ISSUE TITLE
Incorrect Sakai HW Due Data

### ISSUE THREAD

**Issue by Eduardo-Mellado013** [mikeizbicki/cmc-csci145-math166#187]
The due date for Learning From Data homework says 11/2 at midnight on Sakai, but on all other material in the GitHub it states 11/3 at midnight.

![image](https://github.com/user-attachments/assets/3aaafe9d-d69f-4a7b-8c2a-bb5e582654d5)

**Comment by mikeizbicki** [comment]
Whoops... I've updated the date in sakai to Nov 3.  Thanks for letting me know.
