### ISSUE TITLE
Error with torch.sparse.mm calculation

### ISSUE THREAD

**Issue by sarahbashir** [mikeizbicki/cmc-csci145-math166#19]
I'm getting this error when I try to compute the left side of the equation:

```DEBUG:root:computing indices
DEBUG:root:computing values
Traceback (most recent call last):
  File "pagerank.py", line 280, in <module>
    pi = g.power_method(v, alpha=args.alpha, max_iterations=args.max_iterations, epsilon=args.epsilon)
  File "pagerank.py", line 167, in power_method
    lhs = torch.sparse.mm(self.P.t(),xTransposea).t()
  File "/usr/local/lib/python3.8/site-packages/torch/sparse/__init__.py", line 83, in mm
    return torch._sparse_mm(mat1, mat2)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
```

This is the code I have that calculates the left side of the equation:

```
            for k in range(0,max_iterations):
                #implement equation 5.1
                x = x0

                #calculate x^t * a
                xTransposea = x.t() @ a

                lhs = torch.sparse.mm(self.P.t(),xTransposea).t()




```

I think I remember someone else getting this error in office hours but I can't remember how they fixed it. I know that x*P should be (x^t*P^t)^t. Am I not doing that correctly?

**Comment by mikeizbicki** [comment]
I believe this is due to the shapes of P and x not being correct.  Try printing the shapes and seeing if that helps.

**Comment by sarahbashir** [comment]
Hm so I get these as the shapes:
```
shape of x:  torch.Size([6, 1])
shape of p matrix:  torch.Size([6, 6])

```

Should they both be [6,6]?

**Comment by mikeizbicki** [comment]
`x` is not the variable you're multiplying by `P`, you need to check the shape of `xTransposea`.  My guess is that it is a scalar and not a vector. 

I recommend double checking the formula in 5.1 to see that what you're trying to implement is correct, I think the formulas you have in code don't match right now.
