### ISSUE TITLE
Looking for a bit of tech help

### ISSUE THREAD

**Issue by hanaknight** [mikeizbicki/cmc-csci145-math166#21]
heyy, if there's anyone who uses windows & runs their code on vscode & willing to help a homegirl out w some technical processing stuff please let me know, would very much appreciate!

**Comment by mvanis** [comment]
I was able to run it in the default "powershell" terminal (on windows in VSC) using

 C:/Users/"myname"/Documents/Python/python.exe pagerank.py   --data=./lawfareblog.csv.gz --filter_ratio=0.2 --personalization_vector_query='corona' --search_query='-corona'

The terminal you are using will depend on how to input the data files etc. 

Not sure if this can help but I hope it does...

**Comment by hanaknight** [comment]
I think something went wrong when I installed pytorch because there are some modules which couldn't be run? like I got an error message saying 

```
module 'torch.sparse' has no attribute 'sum'
```

**Comment by mvanis** [comment]
I had multiple red lines under torch saying "model torch has no ____ member" but when running I got all the outputs I wanted. 

I used the command 
[row_sums = torch.sparse.sum(self.P, 1)] 

Sorry I do not think I can truly help. 

going to https://stackoverflow.com/questions/51469194/installing-pytorch may help make sure you have pytorch installed.
