### ISSUE TITLE
Upcoming due dates

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci145-math166#23]
Notes (we will complete these notes 100% in lecture)
1. Statistical learning theory II: Wed, 23 Sep
1. Model Zoo: Wed, 30 Sep

Programming assignment due Sunday 4 Oct

**Comment by mikeizbicki** [comment]
I'm changing the due dates of the notes to
1. Statistical learning theory II: Sun, 27 Sep
2. Model Zoo: Sun, 03 Oct
so that you don't have to rush to submit them the same day we finish them in lecture.

**Comment by adhityavenkatraman** [comment]
I'm not sure if this had already been caught, but the deadline for this week's notes is listed for 9/26, when I believe it should be for 9/27. Thanks!

**Comment by mikeizbicki** [comment]
@adhityavenkatraman Whoops, you're right, I made a mistake with sakai.  Thanks for pointing that out.  I've just graded the submissions, and didn't assign any late penalties.
