### ISSUE TITLE
Textbook Access "Error 502"

### ISSUE THREAD

**Issue by mvanis** [mikeizbicki/cmc-csci145-math166#27]
The link (https://www.cs.huji.ac.il/~shais/UnderstandingMachineLearning/) listed in the syllabus for the textbook access is giving me the error "502 Bad Gateway - nginx/1.14.2"

Is the link working for anyone else? Does anyone know how to solve this?

**Comment by mikeizbicki** [comment]
It looks like they're having some problems with their server.  You can also get a copy of the book in the course repo at https://github.com/mikeizbicki/cmc-csci145-math166/blob/fall2020/02_statistical_learning_theory/understanding-machine-learning.pdf

**Comment by mvanis** [comment]
Thank you, the github link has worked.
