### ISSUE TITLE
Friday OH?

### ISSUE THREAD

**Issue by hanaknight** [mikeizbicki/cmc-csci145-math166#29]
Hi prof Izbicki,

Wanted to ask if you have the availability to spare some time on Friday to go over some of the 3b coding assignment?

**Comment by nsamko** [comment]
Same! Morning (9-11am) would work well for me

**Comment by mikeizbicki** [comment]
I'm not available at all before 11am.  I'll tentatively schedule the office hours for 11am, but I'm happy to change it to something else.

**Comment by hanaknight** [comment]
Would after 12pm instead work professor?

**Comment by sarahbashir** [comment]
I have class at that time but am free anytime after 12:10!

**Comment by adhityavenkatraman** [comment]
Could we do 3pm?

**Comment by mikeizbicki** [comment]
3pm seems to work for everyone, so let's do that :)

**Comment by nsamko** [comment]
Is there OH this Friday (10/9)?

**Comment by sarahbashir** [comment]
I also wouldn't mind having some OH :)

**Comment by mikeizbicki** [comment]
Would 2pm work?

**Comment by nsamko** [comment]
yes, thank you!

**Comment by mikeizbicki** [comment]
Great!   I'll be on zoom at 2.

**Comment by gPlacide** [comment]
Will you still be around at 3?
