### ISSUE TITLE
Meet and greet thread

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci145-math166#3]
Your first task in this class is:
1. sign up for github (if you don't already have an account)
1. watch this repo
1. reply to this post telling us what tv show you've been binge watching over summer (or what books you've been reading)

All class communication will go through github, and watching this repo will cause you to get email notifications about everything.

**Comment by mikeizbicki** [comment]
Hi everyone, this is Mike Izbicki :) 

I've been watching *The Expanse* on Amazon Prime, and I reread Patrick Rothfuss's *Name of the Wind* books.  (Gah!!! release the third book already Patrick!)

**Comment by cschulz21** [comment]
Hi all! Connor Schulz here.

Defending Jacob from Apple TV+ (highly recommended)

**Comment by gPlacide** [comment]
Happy first day of class to everyone! This is Placide Gatabazi.

I've been watching an old show that I believe got recently added on Netflix _The Game_. I'm also reading _You Are Not So Smart_ by David McRaney.

**Comment by benfig1127** [comment]
Hey Everyone, I've been binge watching Money Heist, highly recommend it!

**Comment by jerseow** [comment]
Happy first day of class everyone! Jeremy Seow here.

Netflix recommendations: Formula 1: Drive to Survive and Peaky Blinders
Book recommendations: To Sell is Human by Daniel H. Pink

**Comment by nsamko** [comment]
Hi, I am Nina Samko!

Over the summer I've been watching Tarantino movies and read _The Double_ by Fyodor Dostoevsky.

**Comment by hanaknight** [comment]
Happy last first day of the year for seniors! Sabrina Hartono checking in :)
I have so many questions after the latest season of Umbrella Academy (on Netflix). 
Just finished reading _Because Internet_ by Gretchen McCulloch

**Comment by selina-28030** [comment]
Hi, I'm Selina!
I've been watching Normal People, P-Valley, American Gods, and many others. I also really enjoyed Saga by Brian Vaughn and Fiona Staples!

**Comment by rayegleekel** [comment]
Hi everyone! I'm Raye! 

I watched Scandal and How to Get Away with Murder over the summer--highly recommend until about season 6 of both of them...they go downhill after that :) 

Wish I could say I read more/any gripping books this summer.

**Comment by jzhuge99** [comment]
Hi Everyone, hope your first day of classes is going well. 
My name is Jenny and over the summer I watched a lot of Marvel movies as well as The Good Place.

**Comment by elizabethsong** [comment]
Hi guys, I'm Elizabeth!
I also just finished binging How to Get Away with Murder on Netflix.

**Comment by samuellee19** [comment]
Hey, I'm Samuel.

I've been watching Billions as well as some episodes of Mr. Robot!

**Comment by nickludwig** [comment]
Hey all, I'm Nick! 
This summer I've been re-watching schitts creek and veep :]

**Comment by michael-ran** [comment]
Hi everyone, I'm Michael!
This summer, I watched Scandal and Defending Jacob.

**Comment by eruong** [comment]
Hey everyone, my name is Ethan! I've been watching _How to Get Away with Murder_ this summer.

**Comment by StellaLX99** [comment]
Hello everyone, I'm Stella. I've been watching The Disastrous Life of Saiki.K and Madam Secretary this summer.

**Comment by sarahbashir** [comment]
Hi I'm Sarah! I've been watching Ramy on Hulu.

**Comment by ReymonP** [comment]
Hey what's up everyone! 
I've finished watching the show Dark on Netflix over the summer.

**Comment by kielong** [comment]
Hi everyone!
I binge watched the show The Boys on Prime Video.

**Comment by cj2467** [comment]
Whats up! I'm CJ and this summer I finished binging The Americans and I am currently reading East of Eden.

**Comment by ma-alvarado** [comment]
Hey everyone, I'm Matías!

I've worked my way through Narcos and Parks & Rec so far. Totally different but recommend both!

**Comment by oliverc1623** [comment]
Hello! My name is Oliver and I've been watching Sherlock .

**Comment by lenanoguchi** [comment]
Hi! My name is Lena, I have been watching Community and Deathnote (almost finished!)

**Comment by wklein21** [comment]
Hello, hope you all are doing well! Currently working my way through _The Wind-up Bird Chronicle_ by Murakami, and just recently finished The Last Dance on Netflix.

**Comment by adhityavenkatraman** [comment]
Hi all, Adhitya here. I've been catching up on the Good Place this summer.

**Comment by ethanashby** [comment]
Hey everyone, I am 1/2 of the Ethan coalition in Math166! The best show I watched this summer was Homeland (on Amazon Prime Video) and my fave read was The Emperor of All Maladies: A Biography of Cancer. Excited to meet y'all and do some cool data science this semester!

**Comment by natashawong** [comment]
Hello! I'm Natasha. I've been rewatching Black Mirror and Sherlock, and in the process of finishing Indian Matchmaking!

**Comment by gabeu** [comment]
Hi I am Gabe.

I watched Avatar and the Umbrella Academy. I read the Parable of the Sower.

**Comment by jleonard21** [comment]
Hi, I'm Jordan! 
I've been rewatching the Office and Parks & Rec

**Comment by karmishthaseth** [comment]
Hi guys, I'm Karmishtha! I've been binge watching Medici on Netflix this summer and just finished reading the Emperor of all Maladies!

**Comment by maxinebaghdadi** [comment]
Hi! My name is Maxine and this summer I actually have not been watching any TV but I recently just finished reading Stolen Lives: Twenty Years in a Desert Jail by Malika Oufkir and I highly recommend it!

**Comment by nmpatterson22** [comment]
Hey everyone. My name is Nohl Patterson- I have been watching community.

**Comment by cnorth21** [comment]
Hello! My name is Clayton and I have been watching Ramy and reading Dune

**Comment by erik-sal** [comment]
I'm Erik. I don't watch a lot of TV but I watch a lot of League of Legends streamers on Twitch and Youtube.

**Comment by jknaudt21** [comment]
Hi I am Juan Diego. I don't watch much TV and instead played video games over the summer.

**Comment by Tumi0521** [comment]
Hi Everyone,
The name is Tumi. I am currently watching Grace and Frankie with my housemates.
A book I am currently reading is The Shack and Napolean Hills Think and Grow Rich

**Comment by jrod2699** [comment]
Hi, Everyone,
My name is Jorge. I read Kokoro by Natsume Soseki, reread the Harry Potter series, and binged Avatar: The Last Airbender over the summer.

**Comment by mvanis** [comment]
Hey, 
My name is Mirek, and this summer I watched too much TV. I recently found Pen15 on Hulu and its pretty funny.

**Comment by jinkim22** [comment]
Hello,

My name is Jin, and a book I started reading this summer is an algotrading book by Robert Carver.
