### ISSUE TITLE
Questions on SLT 3.3

### ISSUE THREAD

**Issue by oliverc1623** [mikeizbicki/cmc-csci145-math166#30]
Hi I have a question on the SLT programming assignment. For 3.3, I'm a little confused on where to find the approximation error since it's defined as min L_D(h), but the testing error is L_D(hs) for the problem.

**Comment by mikeizbicki** [comment]
In the limit as $m \to \infty$, $h_S \to h^*$, where $h^*$ is the optimal hypothesis in the hypothesis class (the $h$ in your definition of approximation error).  Therefore, the value of $L_D(h_S)$ is a good estimate of the approximation error when $m$ is large.
