### ISSUE TITLE
Pageviews on Github Pages?

### ISSUE THREAD

**Issue by ethanashby** [mikeizbicki/cmc-csci145-math166#35]
Hi Mike! For the final project, if we're looking to post our project on Github pages, is there a simple way to track the number of pageviews? Thanks!

**Comment by mikeizbicki** [comment]
I recommend google analytics as an easy way to track pageviews on any webpage.  Here's google's tutorial on how to get it setup: https://support.google.com/analytics/answer/1008015?hl=en

**Comment by samuellee19** [comment]
Hey, Mike. I hope you had a wonderful Thanksgiving. I would like to ask which metric is considered as Pageview. Does "Event Count" on Google Analytics considered as Pageview?

**Comment by mikeizbicki** [comment]
@samuellee19 Google Analytics should have a number labelled "unique visitors" and that's the number to use.
