### ISSUE TITLE
Answer keys on previous assignments

### ISSUE THREAD

**Issue by gPlacide** [mikeizbicki/cmc-csci145-math166#36]
@mikeizbicki I think that we used to have an issue for previous notes/assignments where you posted answer keys for assignments that had already passed. Would it be possible to get an answer key for the **03b_SLT_programming** assignment?

**Comment by mikeizbicki** [comment]
This is a good question.  Unfortunately, enough people haven't submitted this assignment yet that I don't want to post an answer key.  I tried to leave pretty detailed feedback about each of the questions for everyone's submission, but I'm happy to go over the answers in more detail on zoom.
