### ISSUE TITLE
Interesting Big Data Case Competition 

### ISSUE THREAD

**Issue by benfig1127** [mikeizbicki/cmc-csci145-math166#37]
Hey Class, I got an interesting email over the weekend about a hackathon style competition using Big Data, data analytics, etc in the Healthcare space hosted by Stanford. I might plan on competing if I can find several other people who are willing to participate. Here is the link the competition page. 
[Link](https://www.blueprintdatathon.com/)
Let me know if this looks enticing to any of you and maybe we can put together a 5C team!

![LS_flyer](https://user-images.githubusercontent.com/61296503/96487870-0f37b900-11f2-11eb-8b36-e8d1af1d6af9.png)

**Comment by karmishthaseth** [comment]
I saw this too! I'm down to participate in this!

**Comment by benfig1127** [comment]
Sounds great! I think we need at least 4 people to make a group, so if you know anyone else who is up to it let them know!
