### ISSUE TITLE
Office Hours 10/23

### ISSUE THREAD

**Issue by sarahbashir** [mikeizbicki/cmc-csci145-math166#40]
Would you maybe be available for office hours today at 3pm?

**Comment by adhityavenkatraman** [comment]
Is there anyway we could do it closer to about 5pm?

**Comment by mikeizbicki** [comment]
I'm unfortunately totally booked today, so won't be able to offer office hours.  I will give an extension to Monday for the homework assignment so that anyone who wants to can meet in office hours on Monday.
