### ISSUE TITLE
Getting NaN results when --eta=1e1,1e0

### ISSUE THREAD

**Issue by adhityavenkatraman** [mikeizbicki/cmc-csci145-math166#41]
I'm not sure why, but when I run the GD and SGD experiments for --eta=1e1 and 1e0 at --lambda=1e0, the loss is NaN.  Here's what I'm running for the GD: run train.py --eta=1e1 --lambda=1e0  --T=20 --algorithm=gd --logdir=log_gd. It works when --eta is less than 1e-1, but fails for --eta=1e1, 1e0. I know we're not supposed to get extraneous results so I'm confused as to what is happening here.

When I tried running this with a lambda of 0, I did not get NaN results. 

Is anyone else having this issue?

**Comment by mikeizbicki** [comment]
This is expected behavior.  Increasing the values of lambda can cause the program to achieve NaN.  Explaining this in more detail will require me drawing out some plots, and I'd be happy to do that in a zoom meeting if you'd like.

**Comment by adhityavenkatraman** [comment]
To clarify, would these results then not be extraneous runs?

**Comment by mikeizbicki** [comment]
For the homework submission, I'm asking you to not change lambda at all, and only change eta.  It's great to try out experiments with different lambda, but don't include them in the submission.
