### ISSUE TITLE
Submission Issue w/ HW Assignment

### ISSUE THREAD

**Issue by ethanashby** [mikeizbicki/cmc-csci145-math166#42]
Hi Mike,
I had a problem submitting the screenshots from the programming assignment to Sakai: I could only upload one photo at a time, and now that I have uploaded one screenshot, I can't revise my submission to include the second screenshot. Is there a way to add my second screenshot for resubmission? Thanks!

**Comment by mikeizbicki** [comment]
It seems that a number of people have had problems uploading both screenshots.  If you're having trouble, just email me both of the screenshots and I'll use that to enter your grade in sakai.
