### ISSUE TITLE
Cannot reach congresstweets.jsonl 

### ISSUE THREAD

**Issue by oliverc1623** [mikeizbicki/cmc-csci145-math166#44]
Hello,

I'm trying to download the 20gb file, congresstweets.jsonl, but I'm having some trouble connecting to it, saying "This site can’t be reached". Is there a specific way I'm suppose to be downloading the data? I tried using curl but that's failing to connect to it too. 

Thanks!

**Comment by hanaknight** [comment]
I'm having the same problem and I'm not sure if it's because of a geographical connection blocks

**Comment by nsamko** [comment]
Same!

**Comment by mikeizbicki** [comment]
Hmm... I'd forgotten that CMC's network has been configured to not allow connections to this server from off campus.  The file's also too big for box, so I doubt I'm going to be able to distribute it, sorry.

Unless I can think up another solution, that means that you'll have to use the github repo directly and compute the features yourself.  You'll probably have to let the code run over night in order for it to hit the required number of iterations.  If this is an unexpected burden for anyone, let me know and I'll grant an extension.
