### ISSUE TITLE
Questions on the hw--Transformers library

### ISSUE THREAD

**Issue by gPlacide** [mikeizbicki/cmc-csci145-math166#46]
1. I run into the error below when I tried training the model using the ```t5-small``` feature generator. I'm running it now with the ```albert-base-v2``` and it's running at the moment but I'm not sure if I might run into another error later.

```
Traceback (most recent call last):
  File "train.py", line 172, in <module>
    feature_generator_dimensions = make_features_batch(['this is a test']).shape[1]
  File "train.py", line 167, in make_features_batch
    del encoding['token_type_ids']
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/collections/__init__.py", line 1012, in __delitem__
    def __delitem__(self, key): del self.data[key]
KeyError: 'token_type_ids'
```

**Comment by mikeizbicki** [comment]
As I mentioned in office hours, I'm going to be posting a new dataset that will fix this problem and some other problems that people are running into.  I'll have the fixed version available sometime tonight.
