### ISSUE TITLE
Friday office hours

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci145-math166#5]
Several people have requested office hours on Friday to go over questions about the first notes.  I'll be available on zoom starting at 10AM on Friday, and I'll stay as long as anyone still has questions.

**Comment by mikeizbicki** [comment]
I will have extra Friday office hours again this week starting at 10:30AM.  I have a meeting just before this, so I might be a bit late if the meeting runs over time.

**Comment by jknaudt21** [comment]
What is the link for the office hours? Is it the same one we use for class?

**Comment by mikeizbicki** [comment]
@jknaudt21 Yes, all office hours use the same zoom link as class.

**Comment by mikeizbicki** [comment]
This Friday, I'm not available until after 3pm for office hours.  If anyone would like to meet, just reply here to let me know.

**Comment by mvanis** [comment]
I think I will need to meet for office hours but have a meeting from 3-4. What is the best way to request office hours by appointment?

**Comment by sarahbashir** [comment]
me!! 4 pm is really good for me, if that's not too late!

**Comment by ashleywangg** [comment]
Office hours at 4 PM would also be great for me!

**Comment by mikeizbicki** [comment]
Since 4pm seems to be a good time overall, I'll do then for my office hours Friday instead of 3pm.

@mvanis In general to request a 1-1 meeting, find a time in [my schedule](https://outlook.office365.com/owa/calendar/45eb28fd4e4f45f4b0d120d17676d937@ClaremontMcKenna.edu/a46ebec5e46b4328abcb964af38795935165582125062542146/calendar.html) that we're both free and send me an email asking to meet.
