### ISSUE TITLE
Error in code

### ISSUE THREAD

**Issue by kielong** [mikeizbicki/cmc-csci145-math166#50]
I'm getting this weird error, and I'm not really sure how to fix it. The only part of the code that I changed is calculating the accuracy@k, but the error is coming from another part of the code.
![Screen Shot 2020-11-09 at 1 11 15 PM](https://user-images.githubusercontent.com/46983594/98585813-7266b980-228d-11eb-943b-175b02acb380.png)

**Comment by mikeizbicki** [comment]
Some people have been getting this error when using the `t5-small` model.  I'm not entirely sure why the code works on my machine, but not other people's, but my guess is that we have slightly different versions of some libraries installed.  The fix is to use the `albert-base-v2` model instead.
