### ISSUE TITLE
code crashes at t=408

### ISSUE THREAD

**Issue by jinkim22** [mikeizbicki/cmc-csci145-math166#53]
Hi,

I have tried to run albert three times now on my mac, and have noticed that every run has crashed at step t=408 with this error below:
![Screen Shot 2020-11-11 at 1 59 37 PM](https://user-images.githubusercontent.com/47162507/98869733-19328d80-2427-11eb-8737-146751773087.png)

Also, for reference, this is my code:
![Screen Shot 2020-11-11 at 2 05 49 PM](https://user-images.githubusercontent.com/47162507/98869677-0455fa00-2427-11eb-9121-fbd550653896.png)

Does anyone know why this is crashing?

**Comment by mikeizbicki** [comment]
Hmmm... that's a weird error message.  Threads are how computers implement parallel algorithms, and pytorch uses them to perform parallel matrix multiplications.  My guess is that somehow your system is configured in a way that pytorch that exposed a bug in pytorch.

I think I might have an idea of how to fix it by disabling multithreaded/parallel execution.  Try putting the following line
```
torch.set_num_threads(1)
```
immediately after your `import torch` code.  That will force pytorch not to use multithreading, and so should hopefully fix the problem.  If not, it's okay to submit your runs with results up to t=408.
