### ISSUE TITLE
OS Error too many open files 

### ISSUE THREAD

**Issue by benfig1127** [mikeizbicki/cmc-csci145-math166#54]
@mikeizbicki Im currently working on the server and it seems that something weird is going on and the script isnt closing the json files. Here is the erorr message:
```
OSError: [Errno 24] Too many open files: 'congresstweets/data_filtered/2017-10-12.json'
```
Here are the other related messages (these go on for several hundred lines above):
```
Exception in thread Thread-1044:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
  File "/usr/lib/python3/dist-packages/tensorboard/summary/writer/event_file_writer.py", line 211, in run
  File "/usr/lib/python3/dist-packages/tensorboard/summary/writer/record_writer.py", line 39, in write
  File "/usr/lib/python3/dist-packages/tensorflow_core/python/lib/io/file_io.py", line 106, in write
  File "/usr/lib/python3/dist-packages/tensorflow_core/python/lib/io/file_io.py", line 92, in _prewrite_check
tensorflow.python.framework.errors_impl.ResourceExhaustedError: experiments/congress tweets dataset/events.out.tfevents.1605161284.lambda-server.16882.1043; Too many open files
```
Here is the code that I added for the assignment:
```

		topks = [1,3,5,10,22]
		for k in topks:
			#print('\n')
			#print('output variable type:',type(output))
			#print('output variable shape:',list(output.shape))
			k_predictions_values, k_predictions_indicies=torch.topk(output,k)
			#print(type(k_predictions_indicies))
			#print('current result.shape:',list(k_predictions_indicies.shape))
			hit_count=0
			for i in range(args.batch_size):
				if target[i] in k_predictions_indicies[i]:
					hit_count+=1
			acc_at_k = hit_count/args.batch_size
			
			
			from torch.utils.tensorboard import SummaryWriter
			writer = SummaryWriter('experiments/congress tweets dataset')
			
			tensoboard_display_name='accuracy@'+str(k)
			writer.add_scalar(tensoboard_display_name,acc_at_k,t)

```

Any help would be appreciated :)

**Comment by benfig1127** [comment]
I tried setting the threadding option to 1 as mentioned in the other issue, but it didn't seem to fix anything.

**Comment by selina-28030** [comment]
This worked for me: https://stackoverflow.com/questions/16526783/python-subprocess-too-many-open-files

```
ulimit -Sn 10000
```

**Comment by benfig1127** [comment]
@selina-28030 thanks! Just tried this, and since I am not the server owner I got hit with the "this operation is not permitted, are you root?" (which I am definitely not) LOL , hopefully mike sees this at some point.

**Comment by mikeizbicki** [comment]
Hmmm... I don't see any bugs in the code causing too many open files, and I can't increase the number of files that you're allowed to open on the server.  You'll have to run it on your own machine if you need to do that.

**Comment by benfig1127** [comment]
@mikeizbicki I ended up solving the problem some how, it seemed to be related to how I was writing data to tensorboard, either way I was able to get well over 1k iterations for the assignment.
