### ISSUE TITLE
Accuracy @22

### ISSUE THREAD

**Issue by sarahbashir** [mikeizbicki/cmc-csci145-math166#55]
My tensorboard doesn't output the correct accuracy at k = 22. It correctly calculate the accuracies for the other k's, just not k=22... not sure what could be going on.

<img width="1401" alt="Screen Shot 2020-11-11 at 8 00 49 PM" src="https://user-images.githubusercontent.com/47167558/98902922-70f2e800-246b-11eb-8799-89f9300a1f61.png">
<img width="1399" alt="Screen Shot 2020-11-11 at 8 00 41 PM" src="https://user-images.githubusercontent.com/47167558/98902934-751f0580-246b-11eb-9a26-8fe55cfdc7c0.png">

**Comment by mvanis** [comment]
I think since k=22 the full list of 22 twitter accounts (or something like that) -- it should return 1 (aka its in the list 100% of the time) each time. I may have just demonstrated my lack of understanding... But I hope this helps.

**Comment by sarahbashir** [comment]
oh I completely misread it I though the 1 was 0.1 for the @ 22 graph!! Thank you!! It makes total sense.
