### ISSUE TITLE
text_ii: integer division causing test error to be 0

### ISSUE THREAD

**Issue by cschulz21** [mikeizbicki/cmc-csci145-math166#56]
While trying to do the homework text_ii, I found my test_acc was 0 for k = 1, 3, 5, and 10. At 10 even just guessing blindly it should be at around .45. I believe this is because python was trying to do integer division so any value less than 1 became 0.

To fix this I changed line 352. I replaced:
writer.add_scalar('test_acc/@'+str(k), test_acc[k]/test_dp, epoch)

with:
writer.add_scalar('test_acc/@'+str(k), test_acc[k]/float(test_dp), epoch)

and that seemed to fix the problem. Hope this helps anyone else with the same issue.

**Comment by mikeizbicki** [comment]
Thanks!  It looks like different versions of pytorch perform division differently here.  Your fix should work on all versions of pytorch, so I've uploaded it to github.

See https://github.com/pytorch/pytorch/issues/5411 for a full discussion of this bug.
