### ISSUE TITLE
AttributeError: module 'tensorflow._api.v2.io.gfile' has no attribute 'get_filesystem'

### ISSUE THREAD

**Issue by jinkim22** [mikeizbicki/cmc-csci145-math166#58]
Hi,

I keep having this above error with this log:
![Screen Shot 2020-11-17 at 7 25 47 PM](https://user-images.githubusercontent.com/47162507/99479318-c9faca00-290a-11eb-8349-7d98f9e08420.png)
Also, this ends up not writing anything to the test_acc tensorboard. Should it still be writing 533 steps onto the tensorboard? or is this expected since it crashes before converging?

Thanks,
Jin

**Comment by selina-28030** [comment]
I also had the same issue and inserting this code from this [post](https://github.com/pytorch/pytorch/issues/30966) worked for me:
```
import tensorflow as tf
import tensorboard as tb
tf.io.gfile = tb.compat.tensorflow_stub.io.gfile
```
