### ISSUE TITLE
Speeding Up Hyperparameter Search?

### ISSUE THREAD

**Issue by ethanashby** [mikeizbicki/cmc-csci145-math166#60]
Hi everybody,

Does anyone have tips on how to speed up the search for good hyperparameters? I chose a set of hyperparameters in the suggested ranges of values, and it has taken ~8 hrs to run half a training epoch. I'd like to finish at least one epoch before I quit the process (so I can see what the errors look like), but I'd rather not wait another day... has anyone else faced similar problems and do they have any suggestions for improvement?

Thanks!

**Comment by mikeizbicki** [comment]
Hmm... something has gone very wrong.

It took my laptop (which is an 8 year old junker) 5 minutes to do an epoch with my final choice of hyperparameters.  There are some combinations that may be a bit slower, but nothing more than about 20 minutes.

Make sure that you are using the `1hot` feature generator and that you are using the smaller dataset.  Off the top of my head, those are the two most likely issues to cause such a dramatic slowdown.

**Comment by ethanashby** [comment]
Aha! The 'class_labels.json' file that I was using was the depreciated file containing the labels for the hundreds of senators! When I supplied the new class labels, everything ran much faster!

**Comment by hanaknight** [comment]
Was there supposed to be a new "class_labels.json" file we were supposed to use? I've been trying to do the runs using the "class_labels.json" file from the text generator hw 1

**Comment by mikeizbicki** [comment]
@sabhartono No, there's no new `class_labels.json` file for this assignment.  @ethanashby was referring to the fact that I had to generate a second version of the file for the previous assignment in order to create a smaller dataset.
