### ISSUE TITLE
test_acc tag

### ISSUE THREAD

**Issue by maxinebaghdadi** [mikeizbicki/cmc-csci145-math166#62]
Hi everyone,

When I run my train.py file, on tensorboard, I'm not seeing the test_acc tag. I'm only seeing acc, nnz_fc1, nnz_fc2 and optimization. I'm not really sure what's going on - any ideas?

Thanks! 

Maxine

**Comment by cschulz21** [comment]
Make sure you run it for at least 1.2k iterations. Once it trains on all the data, it tests it and writes the test acc to tensorbord, so it won’t show up until then.

**Comment by maxinebaghdadi** [comment]
Makes sense - thank you!
