### ISSUE TITLE
Sharing Project Links

### ISSUE THREAD

**Issue by jknaudt21** [mikeizbicki/cmc-csci145-math166#64]
Hey everyone, 
Similar to the Pagerank assignment, I think it'd be great if we share our project links in this thread so people can access (and perhaps upvote/like/retweet) everyone else's project. Below are the links where my partner and I published our project:

**-[Project page](https://samuellee19.github.io/CSCI145_Option_Pricing/)**
**-[Reddit post](https://www.reddit.com/r/quant/comments/jzzy0i/deep_learning_application_on_the_blackscholes/)**

We've also posted on Hacker News, but apparently [upvotes from sent links don't register](https://www.quora.com/Why-dont-I-see-upvotes-for-a-link-I-submitted-to-Hacker-News-I-know-several-of-my-friends-voted-for-it), so if you find a post called "**Neural Networks for Option Pricing**" make sure you leave an upvote!

**Comment by selina-28030** [comment]
Hi y'all,

-[Reddit post](https://www.reddit.com/r/dataisbeautiful/comments/k1g5ix/polarity_of_trumps_tweets_in_2020_by_hour_oc/)
-[Github repo](https://github.com/selina-28030/biden_trump_tweets)

Happy Thanksgiving!

**Comment by oliverc1623** [comment]
Hello, here's our project!

- [Project page](https://ethanashby.github.io/Mitochondrial-Richness-Tech-Report-copy.html)
- [Reddit post](https://www.reddit.com/r/dataisbeautiful/comments/k2sxoj/oc_probabilities_of_seeing_a_novel_mitochondrial/)

Cheers!

**Comment by hanaknight** [comment]
[Github repo](https://github.com/p-ai-org/p-jazz) 
Having some problems with reddit, so here's a [FB Post](https://www.facebook.com/100007222517875/posts/2710821225835268/?d=n) 
The post is a public post so we don't have to be friends for you to throw in a few clicks!

**Comment by jleonard21** [comment]
Hi, here are my project links:

- [Github Repo](https://github.com/jleonard21/Final-Project/blob/main/CS145_FinalReport.pdf)
- [Reddit Post](https://www.reddit.com/r/data/comments/k3lcze/how_sentiment_analysis_quantifies_the_social/?utm_source=share&utm_medium=web2x&context=3)

Good luck with finals!

**Comment by gPlacide** [comment]
Hello, here is our project. Leave us a like!!

* [Project Page](https://gplacide.github.io/Sentiment-Analysis/)
* [Facebook Post](https://l.facebook.com/l.php?u=https%3A%2F%2Fgplacide.github.io%2FSentiment-Analysis%2F&h=AT1Yh5mH9vmYXYs2MiAWGVNc4vF8TSJulT4IZXaEFD3fI9OtLzLfXgQcu_FiznfyFAELQunFcozZd3wZBdU19KK8UkXBsv1OPDgl5a0II-SZN_Out86Islqu-XnU8rOsA3h2-650DSXwf3KGp0D-5wii8w&s=1)

Thanks!

**Comment by cj2467** [comment]
Hi everyone, thanks for sharing your links!

[Here is my reddit post](https://www.reddit.com/r/MachineLearning/comments/k6oud4/d_what_machine_learning_techniques_will_fuel_the/)

Thanks for checking it out!

**Comment by cschulz21** [comment]
Heres my Facebook post on Boosting and AdaBoost. I really appreciate all the likes! Good Luck everyone!

[post](https://www.facebook.com/connor.schulz.75/posts/1469546813243338)

**Comment by mvanis** [comment]
I enjoyed looking at everyone's projects and dropping all the likes/pageviews/upvotes I could. Every project I saw posted above was interesting and well done! I hope you enjoy mine a little as well. 


https://www.facebook.com/mirek.vanis/posts/1901262850015028
