### ISSUE TITLE
Lambda Server Question

### ISSUE THREAD

**Issue by sarahbashir** [mikeizbicki/cmc-csci145-math166#65]
Does anyone know how to copy files from the lambda server to your local machine? We've tried a bunch of different scp commands but can't get it to work.

**Comment by gPlacide** [comment]
I used the format below and I was able to copy what I wanted from the server to my machine. Let me know if it doesn't help

`scp [port number] username@134.173.191.241:[location of the file on the server] [where you want the file to be saved]`

**Comment by benfig1127** [comment]
you can also mount a local folder from your computer using ```sshfs``` to gain an interactive file systems where you can simply drag and drop files as if you were in the file explorer on your own computer.
