### ISSUE TITLE
Meet and greet

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci145-math166#71]
Hi everyone!

Your first tasks in this class are to:

1. sign up for github (if you don't already have an account)
1. press the "watch" button at the top of this page
1. reply to this post with a favorite quote of yours

All class communication will go through github, and watching this repo will cause you to get email notifications about everything.

**Comment by mikeizbicki** [comment]
Hey everyone,

This is Mike Izbicki, and one of my favorite quotes is by [Kurt Lewin](https://en.wikipedia.org/wiki/Kurt_Lewin):

> Nothing is quite so practical as a good theory.

**Comment by DestrosCMC** [comment]
Hi everyone,  

My name is Kieran and one of my favorite quotes is:  
> **“We don’t override the models.”**– [Jim Simons](https://en.wikipedia.org/wiki/Jim_Simons_(mathematician))

**Comment by hfmandell** [comment]
Howdy all,

My name is Hannah and one of my favorite quotes is by [Uta Hagen](https://en.wikipedia.org/wiki/Uta_Hagen):

> We must overcome the notion that we must be regular.

**Comment by nickwilson3** [comment]
Hey all,

My name is Nick and here is one of my favorite quotes by [Mark Spitz](https://en.wikipedia.org/wiki/Mark_Spitz):
> “If you fail to prepare, you’re prepared to fail.”

**Comment by Bhargavaa1** [comment]
Hey everyone,

My name is Adi and one quote that I find entertaining is:

>  "Never trust a computer you can’t throw out a window.”-[Steve Wozniak](https://en.wikipedia.org/wiki/Steve_Wozniak)

**Comment by chuckrak** [comment]
Hey all,

My name is Chuck Rak and one of my favorite quotes is from [Mark Twain](https://en.wikipedia.org/wiki/Mark_Twain):

> "We should be careful to get out of an experience only the wisdom that is in it—and stop there; lest we be like the cat that sits down on a hot stove-lid. She will never sit down on a hot stove-lid again—and that is well; but also she will never sit down on a cold one anymore."

**Comment by kingeddy11** [comment]
Hi everyone,

My name is Eddy and my favorite quote is:
```
You miss 100% of the shots you don't take. - Wayne Gretzky
```

**Comment by danimonz** [comment]
Hi I'm Daniel
my favorite quote is: "if you don't got no sauce then you're lost... but you can also get lost in the sauce" - Radric Davis

**Comment by livrenfro** [comment]
hello, my name is liv and my favorite quote is:
> "Once a new technology rolls over you, if you're not part of the steamroller, you're part of the road."   - Stewart Brand

**Comment by KAVentura** [comment]
Hey everyone, I'm Katherine! One of my favorite quotes: 
>  "Learn from yesterday, live for today, hope for tomorrow. The important thing is not to stop questioning." - Albert Einstein

**Comment by ZiangXue** [comment]
Hi everyone, Ziang here. Sharing one of my fav quotes from 孔子 ([Confucius](https://en.wikipedia.org/wiki/Confucius)):

> 学而不思则罔，思而不学则殆。
> To learn without thinking leads to confusion, to think without learning is effort in vain.

**Comment by x-ndy** [comment]
Hi everyone! I go by xandy and one of my fav quotes is likely from [Miles Kington](https://en.wikipedia.org/wiki/Miles_Kington)

> Knowledge is knowing that a tomato is a fruit. Wisdom is not putting it in a fruit salad.

**Comment by QuinceyWilliams** [comment]
Hi Everyone,
I'm Quincey, and one of my favorite quotes is from Seneca:
"We suffer more often in imagination than reality."

**Comment by nishka-ayyar** [comment]
Hi everyone,
I'm Nishka, and here's one of my favorite quotes by [Elvis](https://en.wikipedia.org/wiki/Elvis_Presley):

> When things go wrong, don't go with them.

**Comment by cristywei** [comment]
Hey everyone,

I'm Cristy, and this is one of my favorite quotes:

> One must have chaos in oneself to give birth to a dancing star.

**Comment by nessakiani** [comment]
Hi everybody,

My name is Nessa and one of my favorite quotes is by Marcus Aurelius:

> The happiness of your life depends upon the quality of your thoughts.

**Comment by samchotzen** [comment]
Hi everyone,

I'm Sam and a favorite quote of mine is:

"We are more real in our simple wish to find a way than any destination we could reach. The step between not understanding that and understanding that is as close as we get to happiness" - David Whyte.

**Comment by jaymaliye** [comment]
Hi everyone,

My name is Jay, and one of my favorite quotes is by [Marcus Aurelius](https://en.wikipedia.org/wiki/Marcus_Aurelius):

> Do not disturb yourself by imagining your whole life at once.

**Comment by kevinm126** [comment]
Hi all,
My name is Kevin and one my favorite quote is by [Thomas Edison](https://en.wikipedia.org/wiki/Thomas_Edison): 

> I failed my way to success.

**Comment by ohorban** [comment]
heyo my name is Alex and my favorite quote is by a former student of this class: 

> Holy fucking shit this was a hard class. I had no idea there was so much god damned fucking math involved in a CS class. You should warn students about that.

**Comment by sophiahuangg** [comment]
Hi everyone! My name is Sophia, and one quote I like is by Albus Dumbledore: 

> "It is not our abilities that show us who we are. It is our choices."

**Comment by RuiluGao** [comment]
Hi everyone! My name is Lulu and my favorite quote is from René Descartes:

> Cogito, ergo sum.
> I think, therefore I am.

**Comment by emjuliet** [comment]
Hi everyone. My name is Emily and I like this quote:

"You will face many defeats in life, but never let yourself be defeated" - Maya Angelou

**Comment by emjuliet** [comment]
Love this quote so much!

**Comment by hstuart23** [comment]
Hi everyone! My name is Hannah and my favorite quote is 
"There should be no such thing as boring mathematics." - Edsger Dijkstra
