### ISSUE TITLE
Lambda server access

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci145-math166#78]
Everyone should have an email from me with access credentials to the lambda server.  For all the programming projects in this class, you are encouraged (but not required) to use the lambda server.  Your first programming project (pagerank) will run just fine on either your own laptop or the lambda server, but certain future projects can potentially run much faster on the server.

If you've never used a remote linux machine before, then using the lambda server can be a bit intimidating.  You have three options for learning how to use it:

1. There's 2 tutorials from my data structures class that you can follow:

    1. [using unix/git](https://github.com/mikeizbicki/cmc-csci046/blob/2021spring/week_00/git.md)
    2. [customizing your bash prompt](https://github.com/mikeizbicki/cmc-csci046/blob/2021spring/week_00/lambda-server.md)

1. The QCL will have many students who have used the lambda server, and so you can stop by there for help.

1. I'll be hosting a special office hours session next week Tuesday from 9:30AM-10:30AM dedicated to helping students get started with the lambda server.  If you'd like to come, just let me know (either by email or replying to this post) so that I know if I need to get a bigger room than just my office.

**Comment by KAVentura** [comment]
I would like to come to your special office hours if it is avaliable.
