### ISSUE TITLE
Having trouble creating directory

### ISSUE THREAD

**Issue by Bhargavaa1** [mikeizbicki/cmc-csci145-math166#79]
Hey Mike and the rest of the class,
I am running into a permission denied error when I attempt to make a directory or clone a directory on the lambda server. 
```
abhargava@lambda-server:~$ mkdir 01_computation_Pagerank
mkdir: cannot create directory ‘01_computation_Pagerank’: Permission denied
abhargava@lambda-server:~$ git clone https://github.com/Bhargavaa1/01_computation_Pagerank.git
fatal: could not create work tree dir '01_computation_Pagerank': Permission denied`
```
I have tried using `chmod` but you cannot change the permission settings of a directory that does not exist. Any tips or advice would be greatly appreciated.

Thanks,
Adi

**Comment by mikeizbicki** [comment]
This was related to your password reset.  To do that, I deleted the old user account and created a new one.  The home folder was still assigned to the old, no longer existing account, however.  That's why the new account didn't have write permissions.  This should be fixed now.
