### ISSUE TITLE
Notes 1, Problem 12 + Homework Submission 

### ISSUE THREAD

**Issue by jrod2699** [mikeizbicki/cmc-csci145-math166#8]
Hi, 
I have a couple of queries for problem 12 question 3 of the homework: is the optimal paranthesization dependent on the dimensions of each matrix? Would one paranthesization be preferable over the other because of the number of multiplications necessary to complete the computation? Would it suffice to simply provide an example of what that would look like? Or, is there a different way to approach the problem? (Completely unrelated but) Where do we submit the homework? 

Sorry to pepper you with so many questions but I hope this post helps other students as well!

**Comment by mikeizbicki** [comment]
These are great questions :) 

> is the optimal paranthesization dependent on the dimensions of each matrix?

yes

> Would one paranthesization be preferable over the other because of the number of multiplications necessary to complete the computation?

Exactly right.

> Would it suffice to simply provide an example of what that would look like?

For 12.1, I got the answer $O(mno+mop)$, and 12.2 $O(mnp + nop)$, so you would prefer the former whenever $ mno+mop < mnp + nop$.  The equation can't be simplified any further than that.

You could write the overall runtime of $ABC$ as $O(\min\{mno + mop, mnp+nop\})$.

> Where do we submit the homework?

There should be an assignment called `week_00` in sakai with a place to submit it.
