### ISSUE TITLE
Weird Result with x.squeeze()

### ISSUE THREAD

**Issue by DestrosCMC** [mikeizbicki/cmc-csci145-math166#81]
When running:
```
x = x0.squeeze()
return x.squeeze()
``` 
in ```power_method``` a uniform matrix is returned. 
By commenting out ```x = x0.squeeze()``` the pagerank vector is returned instead. What is the reason this happens?

#80 is the pull request for my change.

**Comment by mikeizbicki** [comment]
`x` is intended to be the `x^k` variable from the paper.  `x0` is the starting vector (`x^0` in the paper).  Maybe for consistencies sake it would have been a bit better to name `x` as `xk`.

You're correct that the output of the power method should be `x` and not `x0`.
