### ISSUE TITLE
Extra Office Hours

### ISSUE THREAD

**Issue by sophiahuangg** [mikeizbicki/cmc-csci145-math166#84]
Hi Mike!

Can I propose for an extra office hours session this Friday sometime after your regular office hours session?

**Comment by mikeizbicki** [comment]
Yes, I can be available anytime before 4pm on Friday for an office hours session dedicated to questions about the first midterm.  I'll let you all respond here with suggestions about times and see if we can come to a consensus.

**Comment by sophiahuangg** [comment]
Going to throw in a suggestion for Friday 12:00pm-1:00pm.

**Comment by QuinceyWilliams** [comment]
I will also throw in a suggestion for Friday 1:00pm-2:00pm.

**Comment by mikeizbicki** [comment]
The "normal" office hours time today is 11am-12pm.  I'll reserve 12pm-1pm for questions dedicated just to the upcoming midterm, and if there's still questions at that point, I'm happy to stay until 2pm.
