### ISSUE TITLE
Assertion Error with task 2.1

### ISSUE THREAD

**Issue by laurenleadbetter** [mikeizbicki/cmc-csci145-math166#87]
Hi,

I've been getting an assertion error when testing task 2.1  and Im not sure what's causing it.
 
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/89829795/190934380-40fe5ee1-4f43-4660-a838-4f2b34fe169f.png">

Would anyone know what's causing this or how to fix it?

**Comment by mikeizbicki** [comment]
The `assert` command on line 117 does nothing if the condition is `True` and raises the `AssertionError` if the condition is `False`.  `assert` is used to ensure that the program maintains "invariants" that should never be broken.  In this case, the invariant that must remain true is that the `v_sum > 0`.  Looking at the definition of `v_sum` on line 116, we see that this means that the sum of all the elements in the `v` vectors must be greater than 0.  (The reason for enforcing this invariant is that Pagerank isn't guaranteed to converge is the `v` vector is the zero vector.)  For some reason, however, it seems like your `v` vector is the zero vector.

**Comment by laurenleadbetter** [comment]
I restarted my vs code and computer and it started running properly.. should've tried that sooner. Thanks for the help.
