### ISSUE TITLE
Notes 1 Qn 18.2

### ISSUE THREAD

**Issue by hanaknight** [mikeizbicki/cmc-csci145-math166#9]
Hi prof Izbicki, I might have missed this during OH but what was the equation you were going to change this one to? As we discussed then, the current expression listed would not work. Further, removing the transpose from the first A would also not work as the second half of the expression has a shape of nn.

**Comment by mikeizbicki** [comment]
A (A^T A) ^ {-1}

**Comment by hanaknight** [comment]
Cool, thanks prof!
