### ISSUE TITLE
Tuesday Midterm Review Session

### ISSUE THREAD

**Issue by DestrosCMC** [mikeizbicki/cmc-csci145-math166#91]
# **Midterm Review Session Tuesday 9/20/22 1:45pm - 2:45pm**  
## *Math Learning Commons (Near Mike's Office)*

Proposed time for tomorrow's optional review session.

**Comment by sophiahuangg** [comment]
Can I propose for 1:15:2:15pm?

**Comment by DestrosCMC** [comment]
> Can I propose for 1:15:2:15pm?

Maybe if Mike is ok with it we combine the two and do 1:15-2:45?

**Comment by mikeizbicki** [comment]
The combined time of 1:15-2:45 sounds good to me.  Come with lots of good questions :)
