### ISSUE TITLE
Extra Office Hours - Midterm Prep

### ISSUE THREAD

**Issue by afroCoderHanane** [mikeizbicki/cmc-csci145-math166#94]
Hey Mike, I am wondering if we could have an additional official hours for prep on Thursday morning for people that could make it today or have additional question. I am proposing 10 AM- 11:30 AM. 
Thanks :)

**Comment by Bhargavaa1** [comment]
I second this and if possible can we extend the hours from 10 AM-12 PM?

**Comment by mikeizbicki** [comment]
Yes, I'll be available from 10AM-12PM tomorrow morning.  We'll start in my office, and if that gets crowded then we'll go to the math commons room again.
