### ISSUE TITLE
PageRank 1 Questions

### ISSUE THREAD

**Issue by Bhargavaa1** [mikeizbicki/cmc-csci145-math166#96]
Hey Mike,
I have a couple of questions from the PageRank 1 Notes:
1) What is the minimal eigenvalue of $\bar{\bar P}$? I believe it's zero based on a couple of examples but this does not hold for every $\bar{\bar P}$ matrix.    
2) Why does the primitivity of $\bar{\bar P}$ guarantee that the PageRank vector exists and is unique?
3) Are all the entries in the PageRank vector non-zero? I believe so because  $\bar{\bar P}$ is irreducible and based on the random surfer model every page/node can be reached from every other node?
4) Is the rank of  $\bar{\bar P} = n$? I am saying False because we can set P to be the Zero matrix with dimensions 2x2 and therefore have all of the elements in $\bar{\bar P}$ be 0.5. Therefore the number of linearly independent rows is 1 and we have a rank that is less than $n$. Based on the rank definition (number of non-zero eigenvalues = rank of the matrix), can we say that eigenvalues other than the top eigenvalue can be repeated?
5) In general, we can have repeated eigenvalues (one eigenvector has multiple eigenvectors) but can we have repeated eigenvectors (one eigenvector has multiple eigenvalues associated with it)?

**Comment by mikeizbicki** [comment]
> 1) What is the minimal eigenvalue of $\bar{\bar P}$? I believe it's zero based on a couple of examples but this does not hold for every $\bar{\bar P}$ matrix.

Correct.

> 2) Why does the primitivity of $\bar{\bar P}$ guarantee that the PageRank vector exists and is unique?

The main thing to know is that primitivity implies a unique top eigenvalue.  (I forget if this is proved or just stated in the paper, but we will take it for granted.)  The pagerank vector is defined as the top eigenvalue of the $\bar{\bar P}$ matrix, and so primitivity directly implies pagerank is unique.

> 3) Are all the entries in the PageRank vector non-zero? I believe so because  $\bar{\bar P}$ is irreducible and based on the random surfer model every page/node can be reached from every other node?

Correct.

> 4) Is the rank of  $\bar{\bar P} = n$? I am saying False because we can set P to be the Zero matrix with dimensions 2x2 and therefore have all of the elements in $\bar{\bar P}$ be 0.5. Therefore the number of linearly independent rows is 1 and we have a rank that is less than $n$. Based on the rank definition (number of non-zero eigenvalues = rank of the matrix), can we say that eigenvalues other than the top eigenvalue can be repeated?

Everything you said is true.

> 5) In general, we can have repeated eigenvalues (one eigenvector has multiple eigenvectors) but can we have repeated eigenvectors (one eigenvector has multiple eigenvalues associated with it)?

The eigenvalue of a particular eigenvector is always unique.

**Comment by Bhargavaa1** [comment]
Thanks for answering and clarifying.
