### ISSUE TITLE
T/F Question 26, 29&30

### ISSUE THREAD

**Issue by ZiangXue** [mikeizbicki/cmc-csci145-math166#98]
For 26: 

The answer to 26 is True, but the pagerank paper said:

"The smaller α is, the faster the convergence."

is the answer wrong or is there some nuance to this question?

For 29 and 30, is there a numerical proof to it? I was thinking that the value for \pi could have changed, but the ranking may remain the same.

**Comment by mikeizbicki** [comment]
> The answer to 26 is True, but the pagerank paper said: "The smaller α is, the faster the convergence." is the answer wrong or is there some nuance to this question?

The runtime bound we have is that $k \le \frac{\log \epsilon}{\log \alpha}$.  This is an upper bound on the runtime, and in particular when $P = 1/n$, then $\bar{\bar P}$ is the same for every value of $\alpha$ and so the runtime will be the same for every value of $\alpha$.

> For 29 and 30, is there a numerical proof to it? I was thinking that the value for \pi could have changed, but the ranking may remain the same.

The ranking will likely remain the same, but the actual values will change.  The intuition is that if you set $\alpha=0$ then $\pi = 1/n$ and so whenever you have a pagerank value higher than $1/n$ and you adjust $\alpha$ closer to 0, the pagerank must go down towards $1/n$.  Similarly, the if the pagerank of a node is less than 1/n, it must raise to reach 1/n.
