### ISSUE TITLE
What does it mean for a Matrix to have NNZ bounds?

### ISSUE THREAD

**Issue by chuckrak** [mikeizbicki/cmc-csci145-math166#99]
When a Matrix A of size n x n is said to have $nnz(A) = O(1)$, I interpret that to mean that the number of non-zero entries in the matrix is a constant. For what matrix would this not be true? Would all matrices not have a constant number of entries? Or does it mean that they do not exceed $n$ entries? Similarly, when $nnz(A) = \Omega(n)$, does that mean it must have at least $n$ non zero entries? Would $\bar{\bar{P}}$ have $nnz(\bar{\bar{P}}) = \Omega(n^2)$?

**Comment by mikeizbicki** [comment]
> When a Matrix A of size n x n is said to have $nnz(A) = O(1)$, I interpret that to mean that the number of non-zero entries in the matrix is a constant. For what matrix would this not be true? Would all matrices not have a constant number of entries?

The confusion here is that when I say "a Matrix A" I don't mean a concrete A but really mean a "family of matrices" satisfying some property.  This is similar to when we say for runtimes for an algorithm that on an input of size $n$ we have a runtime of $O(n)$ even though for any particular input, that input's size is constant, and so we are really talking about a "family of inputs" that have some property.

> Similarly, when $nnz(A) = \Omega(n)$, does that mean it must have at least $n$ non zero entries? Would $\bar{\bar{P}}$ have $nnz(\bar{\bar{P}}) = \Omega(n^2)$?

Both of these statements are correct.
